### PR TITLE
Fix all commands help argument and reformat help texts

### LINKED ISSUE #69: <command> --help is no more working
```sh
nuts install --help
nuts uninstall --help
nuts search --help
```
All of these commands no more show help. What happened?

### PR DESCRIPTION
**Pull request by bacali95**
Closes #69

### CODE REVIEW

**Comment by thevpc** [comment]
Using CoreNutsUtils.isIncludesHelpOption is a bad idea, This is why it was commented. 
Take the example where "--xml" is part of the options. This call will ignore the option.
Perhaps one can do like in DefaultNutsSettingsInternalExecutable but am not sure it works properly (the version i have now is broken)

**Comment by bacali95** [comment]
I think that `--xml` argument and all standard options will not be ignored in this case because it will be already parsed while creating `NutsBootWorkspace`, so I think usinf that helper is safe.
```java
public NutsBootWorkspace(NutsBootTerminal bootTerminal,String... args) {
    LOG=new PrivateNutsLog(bootTerminal);
    this.options=new PrivateBootWorkspaceOptions(LOG)
            .parseArguments(args)
            .setBootTerminal(bootTerminal)
            .build();
    LOG.setOptions(this.options);
    newInstanceRequirements = 0;
}
```

**Comment by thevpc** [comment]
--xml can appear before the command (parsed at boot) or after the command (parsed by the command)
```sh
nuts --xml ls --json
```
in this example, `ls` is executed in json format and not --xml

**Comment by bacali95** [comment]
I didn't where the issue here, do we need to take the last format (--json or --xml...) option?

**Comment by thevpc** [comment]
Do not bother yourself with this limit case. I will accept the changes anyway.

**Pull request merged**
